### ISSUE TITLE
Cannot find module '../../core/dist' error with threads-database

### ISSUE THREAD

**Issue by theefer** [textileio/js-threads#190]
Getting the following when trying to compile a project that depends on @textile/threads-database@0.2.2:

```
ERROR in node_modules/@textile/threads-database/dist/db.d.ts:65:34 - error TS2307: Cannot find module '../../core/dist'.

65     ownLogInfo(): Promise<import("../../core/dist").LogInfo | undefined>;
```

The d.ts file seems to reference an incorrect path outside of its npm package.

**Comment by carsonfarmer** [comment]
Ah cripes, I think this might be an IDE auto-import fail here. I’ll dig in this evening, should be a quick fix.
