### ISSUE TITLE
Docs for withUserKey are incomplete

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#194]
https://textileio.github.io/js-threads/classes/_textile_context.context.html#withapikey

It says it just takes a parameter `value` or string. But think it's something like,

```
{
key: string,
secret: string,
type: 1 == user, 2 == account ? or 0 == account
}
```

**Comment by carsonfarmer** [comment]
Are you possibly referring to https://textileio.github.io/js-threads/classes/_textile_context.context.html#withuserkey? In any case, you are right, these need docs strings across the board.
