### ISSUE TITLE
Publish actual source in packages

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#223]
Some packagers will give you warnings like, 

```
Could not load source file "../../src/thread/index.ts" in source map of "../node_modules/@textile/threads-core/dist/thread/index.js".
```

We should package the actually TS source with the releases too (or maybe something just needs an update in the package.json if they already are).

**Comment by carsonfarmer** [comment]
We can include the typescript sources in our output npm package, but this will increase the size of our bundle (not a huge issue), and isn't helpful outside of source mapping. Maybe we should just not include the source maps in our outputs instead? They really mostly useful for local dev right?

**Comment by andrewxhill** [comment]
yeah exactly. either both all or neither.

it would only increase the download size right? it shouldn't increase final app sizes? 

one benefit of adding them is for our own cross lib development it may be nice for tracking down real issues contained in releases more quickly. yet to be seen though

**Comment by carsonfarmer** [comment]
Ok, I'll look into adding the sources for now, and then maybe we pull them once we have a more stable ecosystem and are more concerned about release size and things like that. And yes, it shouldn't affect bundle size unless someone is building a dev bundle, in which case, they aren't all that concerned about size anyway.
