### ISSUE TITLE
[Where] how can I query based on a date, greater than to fetch data that is been created later than?

### ISSUE THREAD

**Issue by jorishermans** [textileio/js-threads#228]
- Feature Name: Query on date's
- Start Date: 2020-05-26
- RFC PR: [textileio/js-threads#0000](https://github.com/textileio/js-threads/pull)
- Relevant Issue: [textileio/js-threads#0000](https://github.com/textileio/js-threads/issue)

# Summary
[summary]: #summary
For my application I want to query all the data / content created on a specific date ...

# Motivation
[motivation]: #motivation
I want to show the content to the end user that is been created on a specific date or that is been created from a specific date until now.

# Guide-level explanation
[guide-level-explanation]: #guide-level-explanation

Explain the proposal as if it was already included in the library and you were teaching it to another community member. That generally means:

- Introducing new named concepts.
- Explaining the feature largely in terms of examples.
- Explaining how community members should *think* about the feature, and how it should impact the way they use this library. It should explain the impact as concretely as possible.
- If applicable, provide sample error messages, deprecation warnings, or migration guidance.
- If applicable, describe the differences between teaching this to existing developers and new developers.

For implementation-oriented RFCs (e.g. for library internals), this section should focus on how library contributors should think about the change, and give examples of its concrete impact. For policy RFCs, this section should provide an example-driven introduction to the policy, and explain its impact in concrete terms.

# Reference-level explanation
[reference-level-explanation]: #reference-level-explanation

const q = new Where('published').eq(yesterday);

# Drawbacks
[drawbacks]: #drawbacks

Now you can only query on string based values?

# Unresolved questions
[unresolved-questions]: #unresolved-questions

Querying based on dates ...

# Future possibilities
[future-possibilities]: #future-possibilities

**Comment by carsonfarmer** [comment]
If you convert your dates to ISO strings or Unix epocs, these can be queried directly and things like <, >, ===, etc should "just work". We can add some information about this in the docs.

We _could_ also/alternatively do some automatic conversion from Date -> Unix epoc, but I'm generally not a fan of doing magical conversions under the hood...

**Comment by jorishermans** [comment]
And a transformation step in it, that can be added by the user? Then we can define it as a developer and it is up to the program to handle it, and default for dates can be date.getTime and also with date.getTime you can by giving it back to the end user do new Date(timestamp) to construct the object back.

Then you have a layer to transform objects to a writable one and also a step to construct it again ... just a suggestion ...

**Comment by jorishermans** [comment]
Json schema's support date's so why not having that support as well in threadsDB ...

**Comment by carsonfarmer** [comment]
Closing this as 'stale'. I think the date support in ThreadDB is compliant with json-schema?
