### ISSUE TITLE
Event docs on the Database listener lacks any info about the list of types

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#250]
I see in the main docs that I can listen to '**', otherwise, I can't figure out what's available.

**Comment by andrewxhill** [comment]
here's an example https://textileio.github.io/js-threads/classes/_textile_threads_database.database.html#on

actually, clicking on the event type takes you to nowhere

**Comment by carsonfarmer** [comment]
Ah yes, the docs got removed from the main repo, and now only appears to exist here: https://docs.textile.io/threads/#listen. We should maybe just add a link on the readme to the events that https://github.com/EventEmitter2/EventEmitter2 supports? I don't think our tsdocs setup supports linking to external deps...

**Comment by carsonfarmer** [comment]
We could also maybe show some of these ones somewhere: https://github.com/textileio/js-threads/blob/master/packages/database/src/db.spec.ts#L204?

**Comment by carsonfarmer** [comment]
Adding some doc strings to the database class. But additional details should be added to docs.textile.io.

**Comment by carsonfarmer** [comment]
I think this has been addressed to some degree via doc strings and https://github.com/textileio/docs/blob/master/docs/threads/index.md#listen, right @andrewxhill?

**Comment by carsonfarmer** [comment]
Please reopen if needed.
