### ISSUE TITLE
Log key isn't being sent to the remote host peer on adding from address

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#252]
Results in a loop of `create record failed (log not found), retrying...` on the client and an inability to send new messages to the Thread. However, the new peer continues to receive updates fine.

**Comment by carsonfarmer** [comment]
Fixed with https://github.com/textileio/go-threads/pull/370

**Comment by carsonfarmer** [comment]
Existing tests/examples where this error was cropping up should "just work" with latest docker image of go-threads, or by running go-threads master locally. If running go-threads binaries, this fix will come with the next release.
