### ISSUE TITLE
Could not find a declaration file for module 'interface-datastore'

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#284]
When using `@textile/threads-datastore`. Should this be a dependency? I see in the readme, 

    There are also a number of other recommended packages that will make working with Threads in Typescript/Javascript easier:
    `npm i --save interface-datastore datastore-level buffer`

but is it required?

**Comment by carsonfarmer** [comment]
This is a dependency: https://github.com/textileio/js-threads/blob/master/packages/database/package.json#L77

Is this perhaps from following those instructions and installer a more recent version of that lib? I think there's a ticket about updating that one?

**Comment by andrewxhill** [comment]
I see `"interface-datastore": "^1.0.2"` so could be it. I'll try to match and see
