### ISSUE TITLE
Add `withKeyInfo` method to Database

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#293]
It's useful for secure environments that can use API keys directly... if possible.

**Comment by carsonfarmer** [comment]
I'd actually like to see all of these augmentations (convenience static methods) moved to js-hub at some point. Not a priority right now, but those are indeed hub features, so it makes sense to have them there in one place from an organization and ease of updating perspective.

**Comment by andrewxhill** [comment]
This is blocking now. I'm moving most of the tutorials to use the non-signing key variants to make it all easier. So to get the Chat example in, I need this so that I can pass an API Key instead of the userauth object.

**Comment by andrewxhill** [comment]
so docs look like this,

```typescript
const init = (keyInfo: keyInfo, threadID: ThreadID) => {
    const storage = new LevelDatastore(threadID.toString())
    const db = Database.withKeyInfo(keyInfo, storage)
}
```

**Comment by carsonfarmer** [comment]
Ok, I can blast this in this AM.
