### ISSUE TITLE
Don't make Node.js users inject WebSocket into global scope

### ISSUE THREAD

**Issue by ShishKabab** [textileio/js-threads#328]
**Is your feature request related to a problem? Please describe.**
When modifying the global scope, one never knows what conflicts might arise in a bigger project, where multiple packages may try to monkey-patch things.

**Describe the solution you'd like**
Let users pass in the WebSocket implementation in the `Client` constructor.

**Describe alternatives you've considered**
The solution described in the main README.md, `global['WebSocket'] = require('isomorphic-ws')`, which is very icky.

**Comment by carsonfarmer** [comment]
Yeh we've never really liked this solution all that much. Unfortunately, the underlying gRPC client expects a global WebSocket object. We should try to look into ways of passing a an implementation to the underlying client directly.

**Comment by ShishKabab** [comment]
Maybe it's a good idea to file an upstream issue?

**Comment by carsonfarmer** [comment]
Possibly, but not sure that's the right place for the "fix". We could suggest an isomorphic version of the WebSocket transport over there perhaps? I'll think about doing that this afternoon.
