### ISSUE TITLE
Implement document indexing

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-threads#34]
**Why?**
We have document indexing in Go to speed up queries on objects in the materialized views of the threads database. It would be useful to have the same functionality in Javascript. Due to the design of the updates in JS, this should actually be slightly simpler, because we can push the indexing up a level and do it on the way into the database.

**What?**
Using something like https://github.com/eugeneware/level-queryengine on top of an interface-datastore would be quite useful. Automatically using the indexes (rather than having to specify their use) is ideal.

**Describe alternatives you've considered**
Some alternatives out there already existing for creating indexes on (say) leveldb. Would be good to take advantage of one of these. The indexes don't _have_ to be compatible with the Go version, but should provide similar functionality.

**Comment by vasa-develop** [comment]
@carsonfarmer Is this going to be implemented at [database](https://github.com/textileio/js-threads/tree/master/packages/database) level or [store](https://github.com/textileio/js-threads/tree/master/packages/store) level?

**Comment by carsonfarmer** [comment]
I think the best approach is at the database level. Stores can’t assume any particular underlying format. We could do it within the json patch store, but when we do other stores, it’d be nice for the indexes to work still.

**Comment by carsonfarmer** [comment]
For anyone wanting to pick this one up, I'd welcome an RFC-style comment in this thread that lays out a general approach for tackling the work. Something along the lines of https://github.com/rust-lang/rfcs/blob/master/0000-template.md but it doesn't need to be _nearly_ as detailed as that!

**Comment by carsonfarmer** [comment]
Indexing support is actually already available by passing them in the configuration when calling newCollection. These use server-side indexes, rather than local indexes.
