### ISSUE TITLE
Allow client.newDB to pass even if DB exists

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#346]
I've been working through the process of building an app. I found that this flow is going to be common.

```typescript
const db = await Client.withUserAuth(userAuth)
await db.getToken(identity)
```

Next, get a threadID if you've already created one. 

```typescript
const {threadID, existed} = this.getOrCreateThreadID()
```

Where a random threadid is generated if the app didn't already have one cached. 

So then,

```typescript
if (!existed) {
    await db.newDB(threadID)
} 
db.context.withThread(threadID.toString())
```

Those final steps feel confusing. Preferably we could just do,

```
await db.enterDB(threadID) // new if didn't exist, re-join if already existed
```

**Comment by carsonfarmer** [comment]
Maybe just `db.start(threadID?: ThreadID): Promise<void>`. Then the semantics match what you have above, create new if it doesn't exist, connect if it already exists...

**Comment by carsonfarmer** [comment]
Or `open`. Either way, might as well make it the same as we have over on threads-database.
