### ISSUE TITLE
client.listDBs is throwing Error: Method is not accessible, on `onEnd` 

### ISSUE THREAD

**Issue by Tbaut** [textileio/js-threads#374]
**Describe the bug**
client.listDBs is throwing Error: Method is not accessible, on `onEnd` 
> Uncaught (in promise) Error: Method is not accessible
    onEnd index.ts:793

**To Reproduce**
I've a repo [here](https://github.com/Tbaut/textile-playground) where I mostly follow what you do in your test https://github.com/textileio/js-threads/blob/37d8ef1c3ec7a0748465b77d7e29f0cd1494274d/packages/client/src/index.spec.ts

The repo is a CRA for TS, so just clone, `npm install` (or `yarn`), then `yarn start`.
I do the auth with KeyInfo, so you'll need a `.env` file at the root with:
```bash
REACT_APP_HUB_KEY="<your_key>"
REACT_APP_HUB_SECRET="<your_secret>"
```

This is the flow of commands: https://github.com/Tbaut/textile-playground/blob/master/src/components/Threadtest.tsx

Watching the browser console, I get:
![image](https://user-images.githubusercontent.com/33178835/86621178-082bc880-bfbe-11ea-996f-1b0100a8eadd.png)

**Expected behavior**
To list the dbs

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 78

**Additional context**
Note that I tried to run the test in `js-threads` to see if the problem was on my side, but I run into errors that I don't understand. Wanted to make this issue before falling into the rabbit hole.
```bash
npm run test:browser

> @textile/threads@0.0.0 test:browser /home/thib/github/textileio/js-threads
> lerna run --stream test:browser

lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 9 packages: "npm run test:browser"
@textile/context: > @textile/context@0.6.0 test:browser /home/thib/github/textileio/js-threads/packages/context
@textile/context: > polendina --cleanup --timeout 60 src/**/*.spec.ts --webpack-config ../../webpack.test.js
@textile/threads-store: > @textile/threads-store@0.1.16 test:browser /home/thib/github/textileio/js-threads/packages/store
@textile/threads-store: > polendina --cleanup --timeout 60 src/**/*.spec.ts --webpack-config ../../webpack.test.js
@textile/threads-id: > @textile/threads-id@0.1.10 test:browser /home/thib/github/textileio/js-threads/packages/id
@textile/threads-id: > polendina --cleanup  src/**/*.spec.ts --webpack-config ../../webpack.test.js
@textile/threads-store:   polendina ☞   Setting up output directory: /home/thib/github/textileio/js-threads/packages/store/build ...
@textile/threads-id:   polendina ☞   Setting up output directory: /home/thib/github/textileio/js-threads/packages/id/build ...
@textile/context:   polendina ☞   Setting up output directory: /home/thib/github/textileio/js-threads/packages/context/build ...
@textile/threads-id: [
@textile/threads-id:   './src/index.ts\n' +
@textile/threads-id:     "Module not found: Error: Can't resolve '@consento/sync-randombytes' in '/home/thib/github/textileio/js-threads/packages/id/src'\n" +
@textile/threads-id:     "resolve '@consento/sync-randombytes' in '/home/thib/github/textileio/js-threads/packages/id/src'\n" +
@textile/threads-id:     '  Parsed request is a module\n' +
...
```

**Comment by andrewxhill** [comment]
there is a small difference in that particular api when using the Hub versus using your own daemon. 

change it to `listThreads` and see if that works for you.

**Comment by Tbaut** [comment]
Hey Andrew, `listThreads` not being proposed in the TS autocompletion, I used `const dbs = await (client as any).listThreads();` to prevent TS to complain, but then it actually throws:
> Uncaught (in promise) TypeError: client.listThreads is not a function

The problem reported above is not on `listDBs` per se, it's on `onEnd` when calling `listDBs`.

Could this be related with the `context`? The test I mentioned do a `const client = new Client(new Context('http://127.0.0.1:6007'))`

The index.ts:793 pointed by the error is actually this end of this fil [posted here as a gist](https://gist.github.com/Tbaut/92279afa90c1736afefe61a4a36b995e) which implements the `Context` class

**Comment by andrewxhill** [comment]
How are you importing the `Client`?

**Comment by andrewxhill** [comment]
Oh i see now. Yep, there is some `ux` we still need to improve. Can you just change your import from `@textile/threads` to `@textile/hub`? The Hub js library adds the additional method to the Client

**Comment by Tbaut** [comment]
Importing `Client` from `@textile/hub` allowed me to access and see `client.listThreads()` I got one thread with `isdb: true`. 
The method `client.listDBs()` is still available, and still throws. But I guess this is less important now since I can list the threads.

Feel free to close if this is not a concern for you right now.

**Comment by carsonfarmer** [comment]
Yeh this is a bit of a bummer. Would be good to clean this up a bit for the autocompletion aspect alone. It is mentioned in the doc strings that this method is not available via the hub... it is difficult to 'catch' this as the client doesn't know what it is running against. I'm going to leave this open to remind us to find a nicer DX here.

**Comment by carsonfarmer** [comment]
Related: https://github.com/textileio/textile/issues/447
