### ISSUE TITLE
Public-key based identity type

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#375]
`getToken` depends on the `Identity` type which is tricky for a Metamask example.

Metamask will only grant you access to a pubkey and a signing method. Pubkey access looks convoluted a bit, but possible.

It would be nice possibly to create a static generator that was something along the lines of,

```typescript
Identity.from(pubKey, (challenge: string):Promise<UInt8Array>)
```

Such that we could have private key lacking Identities that would work for all the existing examples. 

We should double check what the response type is from web3.personal.sign() too, it might need an explanation to support the required response there.

**Comment by carsonfarmer** [comment]
It should be pretty easy to wrap something like Metamask into a simple class like our libp2pcryptoidentity. However, the above suggestion is pretty nice. We could provide examples for various identity providers.

**Comment by carsonfarmer** [comment]
Can we consider this one "done" @andrewxhill with the existing examples repo?
