### ISSUE TITLE
Can't resolve 'crypto' in micro-aes-gcm

### ISSUE THREAD

**Issue by dp-kb** [textileio/js-threads#389]
https://github.com/textileio/js-threads/blob/21d2b2b96fe9d41ddcdb866beb61d4e48fe2bf56/packages/crypto/package.json#L38

Hi,

This dependency is causing a compilation problem in my Angular 9 project when the node typescript compilation target is the browser. Am I right in assuming this library is intended for the browser?

I get this error:

when starting up my app:
```
ERROR in ./node_modules/micro-aes-gcm/index.js
Module not found: Error: Can't resolve 'crypto' in '/inmanlabs/workspace/pnlp/pnlp-app/node_modules/micro-aes-gcm'
```

With a little digging, it looks like the following lead me to believe this is happening in any node Typescript compilation when the browser is an available target. The `'crypto'` library is not available in the browser which means `'micro-aes-gcm:0.2.0'` is not written as "Universal javascript".
* https://stackoverflow.com/questions/54162297/module-not-found-error-cant-resolve-crypto/54162447
* https://stackoverflow.com/questions/51087330/angular-6-many-cant-resolve-errors-crypto-fs-http-https-net-path-stream
* https://github.com/iden3/snarkjs/issues/17

Unfortunately it looks like 0.2.0 is the latest version: https://github.com/paulmillr/micro-aes-gcm

Do you think I'm interpreting this correctly? Can you find a replacement library? Or poke paulmillr to use something other than the default 'crypto' in micro-aes-gcm?

**Comment by dp-kb** [comment]
Note, if you ever needed to reproduce (not that I'd expect you'd need to)

```
git clone https://github.com/pnlp-network/pnlp /tmp/issue-389
cd /tmp/issue-389
npm install
npm run build

rm -r /tmp/issue-389
```

**Comment by dp-kb** [comment]
Note, to work around this issue in the meantime, you can do the following:

add this to `package.json`: 
```
  "browser": {
    "crypto": false
  },
```

add this pollyfill (in angular `polyfills.ts`):

```
// TODO: https://github.com/textileio/js-threads/issues/389
// remove once issue is fixed and we've upgraded to latest @textile/threads-core
(window as any).global = window;
(window as any).process = {};
(window as any).process = window;
(window as any).process.browser = true;
(window as any).process.version = '';
(window as any).process.versions = { node: false };
(window as any).process.nextTick = (() => {
  const canSetImmediate = typeof window !== 'undefined'
    && (window as any).setImmediate;
  const canPost = typeof window !== 'undefined'
    && window.postMessage && window.addEventListener;
  if (canSetImmediate) {
    return (f: any) => {
      return (window as any).setImmediate(f);
    };
  }
  if (canPost) {
    const queue: any = [];
    window.addEventListener('message', (ev) => {
      const source = ev.source;
      if ((source === window || source === null) && ev.data === 'process-tick') {
        ev.stopPropagation();
        if (queue.length > 0) {
          const fn = queue.shift();
          fn();
        }
      }
    }, true);
    return function nextTick(fn: any) {
      queue.push(fn);
      window.postMessage('process-tick', '*');
    };
  }
  return function nextTick(fn: any) {
    setTimeout(fn, 0);
  };
})();
(window as any).global.Buffer = (window as any).global.Buffer || require('buffer').Buffer;
// END https://github.com/textileio/js-threads/issues/389
```

**Comment by carsonfarmer** [comment]
Hi @dp-kb, glad to see you found a workaround. This is a bit strange to me though. `micro-aes-gcm` should be picking up whether you are in the browser or nodejs and using the appropriate APIs. Does Angular not provide access to the native browser crypto APIs? Maybe this is where it is tripping up: https://github.com/paulmillr/micro-aes-gcm/blob/master/index.js#L7

**Comment by dp-kb** [comment]
Hi @carsonfarmer -

Ah, good spot. Seeing those lines I would expect the crypto library to work in the browser (even in Angular). The error is happening in the Angular native dev server so Angular is probably doing some SSR ts-node compiling and then maybe making an assumption that the browser doesn't have crypto? Anyway... I will do some digging on this and pin down where this issue belongs (might be an Angular issue). Hold off on doing anything about this for the time being, like I said it's non-blocking anyway with the workaround.

Thanks!

**Comment by carsonfarmer** [comment]
Closing this as "no longer relevant" as we have pulled these deps out of the underlying library.
