### ISSUE TITLE
Fix issues with restarting db from threadid vs cold start vs fromInfo

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#396]
each of these cases is slightly different, restart from known threadid, start from randomid, and start from addr before you know the id. the current name mapping kinda breaks this if you try to juggle more than one, since you have to deterministically set the db name on start. or you hit mismatch issues. we fixed one of these last week while sorta creating another. new proposal,

1. scrap db names and just use string of threadid (sure, override if 🤠 )
2. that works for all but fromInfo, so we need to add a method internally that will figure out the addr before finalizing the start. 
3. we could likely move start, startfrominfo to be static methods to just make this really clear and not bother with setting up any db before you are ready to commit to a threadid. or start a new one if you need to change

**Comment by carsonfarmer** [comment]
This was an issue with the previous threads-database implementation. Closing this as "no longer relevant" in favor of work in the ongoing Great Refactor (#414).
