### ISSUE TITLE
Export InstanceList type

### ISSUE THREAD

**Issue by Tbaut** [textileio/js-threads#424]
**Is your feature request related to a problem? Please describe.**
When using Typescript, playing with the result of `client.find()` for instance, I need to type it. It'd be handy to simply import the `InstanceList` from `@textile/threads-client` for instance.
Because this is not available I need to either create the type myself, or use `any` which is not ideal.

**Comment by carsonfarmer** [comment]
No longer relevant as we have opted to unnest these types, so this type isn't required as of 27b51a113883ed775c9a4eb6168e7bc92448ab2f
