### ISSUE TITLE
add a method go check if a collection exists (or check and get info)

### ISSUE THREAD

**Issue by andrewxhill** [textileio/js-threads#505]
some helpful methods would 

- allow me to check if a collection exists by name. e.g. `client.hasCollection(threadID, collectionName)`
- or possibly just get the meta (null meaning non-exist). e.g. `client.getCollection(threadID, collectionName` => (name, schema, instance count maybe)

related to https://github.com/textileio/js-threads/issues/504

**Comment by carsonfarmer** [comment]
The `GetCollectionInfoRequest` should give us what you want here, we just haven't added that API yet I guess? The reply looks like:

```
export namespace GetCollectionInfoReply {
  export type AsObject = {
    name: string,
    schema: Uint8Array | string,
    indexesList: Array<Index.AsObject>,
  }
}
```
