### ISSUE TITLE
ListCollections API not exposed on Client

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-threads#522]
**Describe the bug**
We're missing the listCollections API on the Client class... this is a "bug", as it is available on the Go client: https://github.com/textileio/go-threads/blob/master/api/client/client.go#L398

**To Reproduce**
Can't list existing collections on a threaddb

**Expected behavior**
Should be able to list existing collections on a threaddb

**Additional context**
This is already available on the Go Client: https://github.com/textileio/go-threads/blob/master/api/client/client.go#L398

**Comment by jeffkhull** [comment]
Hi Textile team, I was just trying to access this listCollection function by directly installing `@textile/threads` v0.3.13, but I think I'm doing something wrong.  Can I force update just this package and get this fix, or do I need to wait for a new release of `@textile/hub` before I can use it?

**Comment by andrewxhill** [comment]
It will take a new release of textile/hub, we should have that available later this week. Sorry for the delay.
