### ISSUE TITLE
Deprecate @textile/threads-crypto in favor of @textile/crypto

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/js-threads#553]
Threads crypto is no longer directly needed, as we are moving away from client-side encryption for the time being. We already have an alternative that is recommended in the docs. It is relatively simple to make the switch, but care will have to be taken to ensure compatibility across apps. Note that keys generated with the old lib are completely forward/backwards compatible, the only real difference is the APIs and imports.

**Comment by carsonfarmer** [comment]
@andrewxhill tagging you here also as it is relevant for examples and tests. We should try to move away from the `Libp2pCrypto*` classes in favor of `PublicKey` and `PrivateKey` from `@textile/crypto` over in `@textile/hub`.

**Comment by andrewxhill** [comment]
cool. i think this is already done in all hub libs

**Comment by carsonfarmer** [comment]
Excellent!

**Comment by carsonfarmer** [comment]
Done with #554
