### ISSUE TITLE
Return Action Type and Or Collectionname in the Threads Listen endpoint

### ISSUE THREAD

**Issue by phibar** [textileio/js-threads#556]
In the thread client it would be very cool if you can return also some meta information like collection name and the triggered action.

so response would look like:

`"reply":{
        "instance":{...}
        "actionType":"CREATE",
        "collectionName":"Astronaut"
},
"error":{...}
}`

**Comment by carsonfarmer** [comment]
This information is now added to all listen events: https://github.com/textileio/js-threads/commit/9410d5a6457c94baa4e6d36645ae3d05b5a83d94
